class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = ''
        self.tensorboard_dir = ''
        self.pretrained_networks = ''
        self.lasot_dir = ''
        self.got10k_dir = ''
        self.got10k_val_dir = ''
        self.lasot_lmdb_dir = ''
        self.got10k_lmdb_dir = ''
        self.trackingnet_dir = ''
        self.trackingnet_lmdb_dir = ''
        self.coco_dir = ''
        self.coco_lmdb_dir = ''
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = ''
        self.imagenet_lmdb_dir = ''
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.rgbt234_dir = ''
        self.lasher_dir = ''
        self.gtot_dir = ''
        self.depthtrack_dir = ''
        self.rgbd1k_dir = ''
        self.visevent_dir = ''
